// import Head from 'next/head'
import ArticleList from '../components/ArticleList'

export default function Home({articles}) {
  return (
    <div>
      {/* <Head>
        <title>HOME Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <h1 className="py-2">Welcome to next | Below list of post from json placeholder </h1>
      
      <ArticleList articles={articles} />

    </div>
  )
}


export const getStaticProps = async () => {
const res = await fetch(`https://jsonplaceholder.typicode.com/posts`)
const articles = await res.json();
return{
  props:{
    articles
  }
}
}